theme: jekyll-theme-minimal

title: Wildkatze
logo:  assets/images/logo.png
show_logo: true
description: Multiphysics Simulations
show_downloads: true
avatar: assets/images/logo.png
round-avatar: true
github:
  zip_url: https://github.com/FVUS/wildktaze/blob/main/release/y2022/WildkatzeCFD.zip
  tar_url: https://github.com/FVUS/wildktaze/blob/main/release/y2022/WildkatzeCFD.zip
  another_url: https://github.com/FVUS/wildktaze/blob/main/release/y2022/WildkatzeCFD.zip
  owner_name: Digital Solutions Inc.
  


