theme: jekyll-theme-leap-day

title: Wildkatze CFD
logo: /assets/images/logo.png
show_logo: true
description: Multiphysics Solver.
show_downloads: true
avatar: "/assets/images/logo.png"
round-avatar: true
google_analytics:


